### ISSUE TITLE
Otp table? 

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/ci.erlang.mk#1]
Hi, 
Maybe I miss something but I wonder if using
https://github.com/erlang/otp/blob/master/otp_versions.table would be more useful to list patches.

**Comment by essen** [comment]
I know it exists and perhaps it could generate parts of the `early_plugins.mk` file, but at this point it's just more convenient for me to maintain it manually. It takes just a minute.

**Comment by crownedgrouse** [comment]
No problem.
 This file could be downloaded when older than kerl, and so update the patches list found in kerl output. Just food for thought

**Comment by essen** [comment]
I do not want to use it fully dynamic, if I ever do it'll end up generating part of the plugin when a new release comes in. This repository is also useful for quickly searching through release notes, for example.

**Comment by essen** [comment]
It is now updated automatically via a GH action. It fetches the OTP repository and lists tags then checks what is new.

Automatic cleanup of builds has been dropped, it doesn't make much sense anymore in the days of GH actions with its cache, and erlef/setup-beam.
